version: 2

models:

  - name: stg_players
    description: Contains cleaned player data

    columns:

      - name: player_id
        description: Unique player identifier
        tests:
          - unique
          - not_null

      - name: team_id
        tests:
          - relationships:
              arguments:
                to: ref('stg_teams')
                field: team_id

      - name: player_name
        description: Player full name